site_name: Learning Paths Handbook - structuring lifelong learning journeys
nav:
    - About: index.md
    - 6-steps Protocol - Guidelines:
      - "Introduction": chapters/introduction.md
      - "Step 1": chapters/chapter_01.md
      - "Step 2": chapters/chapter_02.md
      - "Step 3": chapters/chapter_03.md
      - "Step 4": chapters/chapter_04.md
      - "Step 5": chapters/chapter_05.md
      - "Step 6": chapters/chapter_06.md
      - "References": chapters/references.md
    - Case studies: []
    - ELIXIR Training Platform (connections and integration):
      - "ELIXIR Training Life Cycle": []
      - "ELIXIR Training materials on How to design Learning Paths": []
      - "ELIXIR TeSS (Training eSupport System)": []
      #  - "Follow up training": follow_up_training.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: loredanalepera/Learning-Paths-Handbook
repo_url: https://loredanalepera.github.io/Learning-Paths-Handbook/
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  - addbioschemas

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
